apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - postgres-statefulset.yaml
  - backend-service.yaml
  - frontend-service.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - configmap.yaml
  - ingress.yaml

# NO images section here!
# Overlays will define the actual images
