apiVersion: v1
kind: ConfigMap
metadata: 
  name: job-board-config
  namespace: job-board
data:
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "jobboard"

  # Backend configuration
  BACKEND_PORT: "3001"

  # Frontend configuration
  REACT_APP_API_URL: "http://localhost:30001"
