apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-pvc
  namespace: job-board
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3 # Use EBS GP3 storage class
  resources:
    requests:
      storage: 5Gi
