apiVersion: v1
kind: Secret
metadata: 
  name: job-board-secrets
  namespace: job-board
type: Opaque
data:
  # jobboard (base64 encoded)
  DB_USER: am9iYm9hcmQ=
  
  # jobboard123 (base64 encoded)
  DB_PASSWORD: am9iYm9hcmQxMjM=
  
  # jobboard (base64 encoded)
  POSTGRES_DB: am9iYm9hcmQ=
  
  # jobboard (base64 encoded)
  POSTGRES_USER: am9iYm9hcmQ=
  
  # jobboard123 (base64 encoded)
  POSTGRES_PASSWORD: am9iYm9hcmQxMjM=
